### ISSUE TITLE
RISC-V build failure: "GCC version 13 or higher is required on RISC-V"

### ISSUE THREAD

**Issue by knn-k** [eclipse/omr#8308]
Recent PR build jobs on RISC-V failed with the following error, starting from https://ci.eclipse.org/omr/job/PullRequest-linux_riscv64/732/ on June 24:

```
[2026-06-24T16:35:24.776Z] In file included from /home/jenkins/workspace/Build/compiler/runtime/OMRCodeCache.cpp:29:
[2026-06-24T16:35:24.776Z] /home/jenkins/workspace/Build/include_core/AtomicSupport.hpp:64:2: error: #error "GCC version 13 or higher is required on RISC-V"
[2026-06-24T16:35:24.776Z]    64 | #error "GCC version 13 or higher is required on RISC-V"
[2026-06-24T16:35:24.776Z]       |  ^~~~~
```

**Comment by hzongaro** [comment]
According to the most recent failing build https://ci.eclipse.org/omr/job/PullRequest-linux_riscv64/738

```
20:59:16  -- The CXX compiler identification is GNU 11.4.0
20:59:16  -- The C compiler identification is GNU 11.4.0
```

The last successful build — https://ci.eclipse.org/omr/job/PullRequest-linux_riscv64/731 — reports

```
18:54:58  -- The CXX compiler identification is GNU 13.3.0
18:54:58  -- The C compiler identification is GNU 13.3.0
```

**Comment by janvrany** [comment]
The failing code was introduced in PR #8196.

Also, successful builds run on `riscv-build2` whereas failing on `riscv-build1`.

I have opened an issue at EF: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/work_items/7628

**Comment by knn-k** [comment]
RISC-V builds are OK now.  Closing.
