### PR TITLE
AArch64: Add ARM64RegBranchInstruction for br/blr/ret

### PR DESCRIPTION
**Pull request by knn-k**
This commit adds ARM64RegBranchInstruction for aarch64 branch
instructions that take a register as the target address.
It also introduces a new opcode that represents a return from a method,
which is separate from the opcode for aarch64 machine instruction "ret".

Signed-off-by: knn-k <konno@jp.ibm.com>

### CODE REVIEW

**Comment by knn-k** [comment]
This commit also removes the redundant `_conditions` member and its related functions from `ARM64DepInstruction` because the parent `OMR::ARM64::Instruction` class has them.

**Comment by knn-k** [comment]
The new opcode is named as `retn`.  It has to be separate from the machine instruction name `ret`, and the full-spelled `return` causes a C++ compilation error.

**Comment by knn-k** [comment]
Opcode `fence` is introduced in #3020.

**Comment by knn-k** [comment]
Removed "WIP:".

**Comment by knn-k** [comment]
The Travis CI build failed with this message:
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

**Comment by knn-k** [comment]
Rebased to the latest level for resolving conflicts caused by merging #3020.

**Comment by 0xdaryl** [comment]
@genie-omr build aarch64
