### PR TITLE
Update Port.cpp and omrsharedhelper.c to fix gcc11 compilation

### PR DESCRIPTION
**Pull request by pshipton**
The code fails to compile on zlinux with gcc 11.2 without fixes.
```
Port.cpp: In static member function 'static RCType
Port::omrfile_stat(const char*, unsigned int, J9FileStat*)':
Port.cpp:691:14: error: narrowing conversion of '4283649346' from
'unsigned int' to 'int'
[https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wnarrowing]
  691 |         case 0xFF534D42: /* CIFS_MAGIC_NUMBER */
      |              ^~~~~~~~~~
```

This one fails to compile on 32-bit.
```
In file included from /usr/include/string.h:637,
                 from ./unix/omrsharedhelper.c:34:
./unix/omrsharedhelper.c: In function 'omr_unlinkControlFile':
./unix/omrsharedhelper.c:419:9: error: '__builtin_strncpy' specified
bound depends on the length of the source argument
[https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wstringop-truncation]
  419 |         strncpy(originalErrMsg, currentErrMsg, msgLen);
      |         ^~~~~~~
./unix/omrsharedhelper.c:413:26: note: length computed here
  413 |         int32_t msgLen = strlen(currentErrMsg);
      |                          ^~~~~~~~~~~~~~~~~~~~~
```

### CODE REVIEW

File: tools/tracegen/Port.cpp [hunk 1]
```diff
@@ -688,7 +688,7 @@ Port::omrfile_stat(const char *path, unsigned int flags, struct J9FileStat *buf)
 	/* Detect remote filesystem types */
 	case 0x6969: /* NFS_SUPER_MAGIC */
 	case 0x517B: /* SMB_SUPER_MAGIC */
-	case 0xFF534D42: /* CIFS_MAGIC_NUMBER */
+	case (int)0xFF534D42: /* CIFS_MAGIC_NUMBER */
```
[the remark this answers is not in the document]
Comment (pshipton) [reply tools/tracegen/Port.cpp:691]: It doesn't work, you still get the same error `error: narrowing conversion of '4283649346' from
'unsigned int' to 'int'`. Ref http://vmfarm.rtp.raleigh.ibm.com/job_output.php?id=72939611

[the remark this answers is not in the document]
Comment (babsingh) [reply tools/tracegen/Port.cpp:691]: `switch ((unsigned int)statfsbuf.f_type) {` should fix it and prevent loss of data.

[the remark this answers is not in the document]
Comment (babsingh) [reply tools/tracegen/Port.cpp:691]: we can also add `u` to the `case` statements:
```
	switch ((unsigned int)statfsbuf.f_type) {
	/* Detect remote filesystem types */
	case 0x6969u: /* NFS_SUPER_MAGIC */
	case 0x517Bu: /* SMB_SUPER_MAGIC */
	case 0xFF534D42u: /* CIFS_MAGIC_NUMBER */
```

[the remark this answers is not in the document]
Comment (pshipton) [reply tools/tracegen/Port.cpp]: That works, tested it on all the Linux platforms, with and without gcc11 on z.

**Comment by babsingh** [comment]
jenkins build all

**Comment by babsingh** [comment]
PR builds look good. Only the below known failure is seen.
- https://github.com/eclipse/omr/issues/7181

**Review by babsingh — APPROVED** [review]
