### ISSUE TITLE
JitBuilder PPC LE CI Failure: multiple definition of `unknown helper (trampoline)'

### ISSUE THREAD

**Issue by lmaisons** [eclipse/omr#1748]
Introduced by #1612 

Building static ELF tests requires running dynamic call test.  Call doesn't work on platforms without trampoline support.
