### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by babsingh** [eclipse/omr#2857]
The following compile error is seen:
```
In file included from ../../fvtest/omrGtestGlue/omrTest.h:49,
                 from testHelpers.hpp:43,
                 from omrvmemTest.cpp:37:
../../third_party/gtest-1.8.0/include/gtest/gtest.h: In function 'testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = int, T2 = long unsigned int]':
../../third_party/gtest-1.8.0/include/gtest/gtest.h:1459:   instantiated from 'static testing::AssertionResult testing::internal::EqHelper<true>::Compare(const char*, const char*, const T1&, const T2&, typename testing::internal::EnableIf<(! testing::internal::is_pointer::value)>::type*) [with T1 = int, T2 = uint64_t]'
omrvmemTest.cpp:3695:   instantiated from here
../../third_party/gtest-1.8.0/include/gtest/gtest.h:1392: error: comparison between signed and unsigned integer expressions
make[3]: *** [omrvmemTest.o] Error 1
make[3]: Leaving directory `/tmp/bld_394478/bld_linux_x86-64_cmprssptrs/omr/fvtest/porttest'
make[2]: *** [fvtest/porttest] Error 2
make[2]: Leaving directory `/tmp/bld_394478/bld_linux_x86-64_cmprssptrs/omr'
make[1]: *** [tests] Error 2
make[1]: Leaving directory `/tmp/bld_394478/bld_linux_x86-64_cmprssptrs/omr'
make: *** [omr] Error 2
```

The source of the compile error:
```
omrvmemTest.cpp:3695: EXPECT_EQ(0, size) ... //T1 = int, T2 = uint64_t
```

The culprit changes were introduced in https://github.com/eclipse/omr/pull/2796.
