### PR TITLE
Bump Azure x64 build to macOS-latest

### PR DESCRIPTION
**Pull request by AdamBrousseau**

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
@0xdaryl @knn-k 
Using MacOS-latest fails to compile
```
error: 'sprintf' is deprecated
```

**Comment by 0xdaryl** [comment]
Build failures should be fixed by #6907.

**Comment by knn-k** [comment]
`sprintf()` was deprecated with Xcode 14.
See https://github.com/eclipse-openj9/openj9/issues/16517

**Comment by knn-k** [comment]
I tried building OMR on macOS with Xcode 14, and found there was another file that fails with `sprintf()`.

**Comment by knn-k** [comment]
#6907 has been merged, but it seems some more work is required for `sprintf()`.

```
2023-03-02T11:48:44.8196830Z /Users/runner/work/1/s/compiler/cs2/timer.h:762:7: error: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Werror,-Wdeprecated-declarations]
2023-03-02T11:48:44.8198590Z       sprintf(pname, "%s %s", phase, name);

2023-03-02T11:48:44.8220570Z /Users/runner/work/1/s/compiler/env/TRMemory.hpp:1127:20: error: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Werror,-Wdeprecated-declarations]
2023-03-02T11:48:44.8222620Z          offset += sprintf(line+offset, "%12llu ", (long long unsigned int)bytes);
```

**Comment by knn-k** [comment]
I cannot reproduce the build errors in my previous comment.  I see the warning messages with deprecated `sprintf()` when I build OMR libraries and test programs on my M1 Mac, but they are not errors but just warnings.

**Comment by knn-k** [comment]
`OMR_WARNINGS_AS_ERRORS` is ON by default, but it is turned off on AArch64 macOS for some components.  That is the reason why I could not reproduce the build error in my environment.
I opened PR #6915 as a workaround for the macOS-latest environment.

**Comment by knn-k** [comment]
#6915 has been merged, and I re-ran the check on x86-64 macOS.
https://github.com/eclipse/omr/pull/6910/checks?check_run_id=11808897296
Its build completed successfully.  See Issue #6516 for the socket test failures in porttest.

**Comment by knn-k** [comment]
The copyright line in azure-pipelines.yml needs to be updated.

**Review by knn-k — APPROVED** [review]

**Comment by babsingh** [comment]
re https://github.com/eclipse/omr/pull/6910#issuecomment-1457312262:

The Mac OS failure is not related to the socket test failures from https://github.com/eclipse/omr/issues/6516. This PR introduces a new failure which is documented in https://github.com/eclipse/omr/issues/6924.
