### ISSUE TITLE
LinkageTest.cpp fails to compile on gcc 4.4.6 and 4.4.7

### ISSUE THREAD

**Issue by dchopra001** [eclipse/omr#2152]
I've tried compiling on x86 and z, and am getting the following compilation failures :

```
/gsa/tlbgsa/home/d/c/dchopra/development/omr/compiler/ras/DebugCounter.hpp: In constructor ‘TR::DebugCounterGroup::DebugCounterGroup(TR_PersistentMemory*)’:
/gsa/tlbgsa/home/d/c/dchopra/development/omr/compiler/ras/DebugCounter.hpp:250: warning: deprecated conversion from string constant to ‘char*’
/gsa/tlbgsa/home/d/c/dchopra/development/omr/fvtest/compilertriltest/LinkageTest.cpp: In member function ‘void LinkageTest_SystemLinkageParameterPassingFourArg_Test<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = double]’:
/gsa/tlbgsa/home/d/c/dchopra/development/omr/fvtest/compilertriltest/LinkageTest.cpp:154:   instantiated from here
/gsa/tlbgsa/home/d/c/dchopra/development/omr/fvtest/compilertriltest/LinkageTest.cpp:118: error: address of overloaded function with no contextual type information
/gsa/tlbgsa/home/d/c/dchopra/development/omr/fvtest/compilertriltest/LinkageTest.cpp: In member function ‘void LinkageTest_SystemLinkageParameterPassingSingleArg_Test<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = double]’:
/gsa/tlbgsa/home/d/c/dchopra/development/omr/fvtest/compilertriltest/LinkageTest.cpp:154:   instantiated from here
/gsa/tlbgsa/home/d/c/dchopra/development/omr/fvtest/compilertriltest/LinkageTest.cpp:76: error: address of overloaded function with no contextual type information
/gsa/tlbgsa/home/d/c/dchopra/development/omr/fvtest/compilertriltest/LinkageTest.cpp: In member function ‘void LinkageTest_InvalidLinkageTest_Test<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = double]’:
/gsa/tlbgsa/home/d/c/dchopra/development/omr/fvtest/compilertriltest/LinkageTest.cpp:154:   instantiated from here
/gsa/tlbgsa/home/d/c/dchopra/development/omr/fvtest/compilertriltest/LinkageTest.cpp:62: error: address of overloaded function with no contextual type information
/gsa/tlbgsa/home/d/c/dchopra/development/omr/fvtest/compilertriltest/LinkageTest.cpp: In member function ‘void LinkageTest_SystemLinkageParameterPassingFourArg_Test<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = float]’:
/gsa/tlbgsa/home/d/c/dchopra/development/omr/fvtest/compilertriltest/LinkageTest.cpp:154:   instantiated from here
/gsa/tlbgsa/home/d/c/dchopra/development/omr/fvtest/compilertriltest/LinkageTest.cpp:118: error: address of overloaded function with no contextual type information
/gsa/tlbgsa/home/d/c/dchopra/development/omr/fvtest/compilertriltest/LinkageTest.cpp: In member function ‘void LinkageTest_SystemLinkageParameterPassingSingleArg_Test<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = float]’:
/gsa/tlbgsa/home/d/c/dchopra/development/omr/fvtest/compilertriltest/LinkageTest.cpp:154:   instantiated from here
/gsa/tlbgsa/home/d/c/dchopra/development/omr/fvtest/compilertriltest/LinkageTest.cpp:76: error: address of overloaded function with no contextual type information
/gsa/tlbgsa/home/d/c/dchopra/development/omr/fvtest/compilertriltest/LinkageTest.cpp: In member function ‘void LinkageTest_InvalidLinkageTest_Test<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = float]’:
...
...
```

I'm able to successfully compile and run on both platforms when using gcc 5.4.0 though.

**Comment by dchopra001** [comment]
^ Looked at this today. Problem seems to be that we can't provide a reference to a templated function on our older compilers.
