### PR TITLE
RISC-V: fully-qualify evaluators in OMRTreeEvaluatorTable.hpp

### PR DESCRIPTION
**Pull request by janvrany**
This commit fixes compilation errors introduced in 91d90b2323dd430020557e4df4b59160fa254635

### CODE REVIEW

**Comment by 0xdaryl** [comment]
A genie build is not required as this is a RISC-V specific change.

**Review by 0xdaryl — APPROVED** [review]
