### ISSUE TITLE
32 bit arm builds broken, missing include

### ISSUE THREAD

**Issue by JamesKingdon** [eclipse/omr#2864]
Now that the Java 9 release has been restored at AdoptOpenJDK I tried running a travis build for armhf, but it failed attempting to compile HookGen.cpp:

```
In file included from HookGen.cpp:33:0:
HookGen.hpp:32:23: fatal error: pugixml.hpp: No such file or directory
 #include "pugixml.hpp"
```

Any ideas what I'm missing for that file?

**Comment by dnakamura** [comment]
The cmake travis builds are not set up for arm (well cross-compiling to arm). I believe the support is there in the cmake infrastructure,  but it does take a bit of work (since hook and trace gen ) need to be built separately (so they are not cross-compiled).

**Comment by youngar** [comment]
@JamesKingdon Any update on this? Were you running an OMR or OpenJ9 travis build?  CMake or Autoconf based build?  We have a bit of documentation on [how to cross compile](https://github.com/eclipse/omr/blob/master/doc/BuildingWithCMake.md#cross-compiling-omr) with CMake based builds, which might be helpful.

**Comment by JamesKingdon** [comment]
It's an openJ9 build which I believe is autoconf based. I suspect the problem above is a missing dependency in the dockerfile, but I haven't had time to look into it.

Example failing build

https://travis-ci.org/JamesKingdon/openj9-openjdk-jdk10/builds/435712666

**Comment by youngar** [comment]
It looks like your build is failing to properly configure the local build tools:
```
config.status: executing toolconfigure commands
checking build system type... x86_64-pc-linux-gnu
checking OMR_BUILD_OS... linux
checking OMR_BUILD_ARCH... x86
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/root/openj9-openjdk-jdk10/build/linux-arm-normal-server-release/vm/omr/tools':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
```
After failing to configure the build tools, it tries to compile them anyways, resulting in some very incorrect compilation commands:
```
g++    -c    -o FileReader FileReader.cpp
g++    -c    -o HookGen HookGen.cpp
In file included from HookGen.cpp:33:0:
HookGen.hpp:32:23: fatal error: pugixml.hpp: No such file or directory
 #include "pugixml.hpp"
```
PugiXML is checked into `third_party`, so if the compile command was correct, there would be no problem finding pugixml.hpp.  I believe that current OpenJ9 travis builds compile OMR with CMake, not with autoconf.

**Comment by JamesKingdon** [comment]
Ok, this must be something that changed during the period that Adopt wasn't serving up Java 9 JDKs, as the build used to work before that. The last working build was May 14.

**Comment by youngar** [comment]
I'm not sure when or why this build broke :( Looking back at a working build, this is what it should look like:
```
config.status: executing toolconfigure commands
checking build system type... x86_64-pc-linux-gnu
checking OMR_BUILD_OS... linux
checking OMR_BUILD_ARCH... x86
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
...
configure: creating ./config.status
config.status: creating toolconfigure.mk
config.status: creating toolconfig.h
# Force the timestamps of unchanged files to be updated
touch include_core/omrcfg.h include_core/omrversionstrings.h omrmakefiles/configure.mk ./omr.rc tools/toolconfigure.mk CONFIGURE_SENTINEL_FILE
```
```
g++  -I. -I../../third_party/pugixml-1.5  -DUT_DIRECT_TRACE_REGISTRATION  -DLINUX -D_REENTRANT -D_FILE_OFFSET_BITS=64 -DJ9HAMMER -c  -MMD -MP -fno-exceptions -fno-rtti -fno-threadsafe-statics -fPIC -m64 -Wreturn-type -Werror -Wall -Wno-non-virtual-dtor -O3 -fno-strict-aliasing   -o HookGen.o HookGen.cpp
g++  -I.  -DUT_DIRECT_TRACE_REGISTRATION  -DLINUX -D_REENTRANT -D_FILE_OFFSET_BITS=64 -DJ9HAMMER -c  -MMD -MP -fno-exceptions -fno-rtti -fno-threadsafe-statics -fPIC -m64 -Wreturn-type -Werror -Wall -Wno-non-virtual-dtor -O3 -fno-strict-aliasing   -o CFileWriter.o CFileWriter.cpp```

**Comment by youngar** [comment]
We are planning on deleting the autoconf build system very soon, so future work should be towards cross compiling with the CMake build system.

**Comment by JamesKingdon** [comment]
Ok, I guess I'll put that on the winter 'todo' list. Thanks for looking into it.

Is this line of output specific to the autoconf old way of doing things?

`checking whether we are cross compiling... configure: error: in `/root/openj9-openjdk-jdk10/build/linux-arm-normal-server-release/vm/omr/tools':
`

**Comment by youngar** [comment]
Yeah, that line is specific to autoconf.  CMake platform detection looks like this:
```
+cmake -Wdev -G Ninja -DOMR_ENV_DATA32=ON -DOMR_DDR=OFF -DOMR_JITBUILDER=OFF -C../cmake/caches/Travis.cmake ..
loading initial cache file ../cmake/caches/Travis.cmake
-- Starting with CMake version 3.9.2
-- Found Git: /usr/bin/git (found version "2.15.1") 
-- The CXX compiler identification is GNU 4.8.5
-- The C compiler identification is GNU 4.8.5
-- Check for working CXX compiler: /usr/lib/ccache/g++
-- Check for working CXX compiler: /usr/lib/ccache/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
```

**Comment by rwy0717** [comment]
Hey @JamesKingdon, I'm doing some house cleaning, and closing old build system issues. This issue hasn't been updated in some time. Is it still relevant? (sorry for the issue necromancy)

**Comment by JamesKingdon** [comment]
Hi Robert, thanks for taking the time to clean up these old issues. I've dropped out of ARM related activities, so I have no idea what the current status is on this. I'll close this issue as it's likely any attempts to get arm going again will need to start from a clean slate.
