### PR TITLE
RISC-V: fix compilation error introduced by f3c45015f6

### PR DESCRIPTION
**Pull request by janvrany**

### CODE REVIEW

**Review by mstoodle — APPROVED** [review]
lgtm

**Comment by mstoodle** [comment]
RISC-V specific change, and we have no CI resources for this platform, so will just merge.
