### PR TITLE
Enable tril tests on Windows

### PR DESCRIPTION
**Pull request by wbh123456**
Tril Tests are currently not running on Windows. Fix Tril Tests errors that occurs under Windows and enable it for Windows Azure builds. Note that `Tril Test` refers to the two ctest units in `fvtest`: `comptest` and `triltest`.

Details about the fix is stated in issue #5324 

- [x] Enable tril tests (`comptest` and `triltest`) on Windows build in `Azure build`
- [x] Fix/skip failing test cases in `comptest` on Windows
- [x] Fix/skip failing test cases in `triltest` on Windows
- [x] Skip failing test cases in `compilertest` see details in #5378

Issue: #5324
Signed-off-by: Bohao(Aaron) Wang <aaronwang0407@gmail.com>

### CODE REVIEW

**Comment by wbh123456** [comment]
The appveyor and the Azure omr windows pipeline are both having include problems:
```
         c:\projects\omr\fvtest\tril\tril\ast.hpp(27): fatal error C1083: Cannot open include file: 'OMR/TypeTraits.hpp': No such file or directory [C:\projects\omr\fvtest\tril\tril\tril.vcxproj]
         c:\projects\omr\fvtest\tril\tril\ast.hpp(27): fatal error C1083: Cannot open include file: 'OMR/TypeTraits.hpp': No such file or directory [C:\projects\omr\fvtest\tril\tril\tril.vcxproj]
         c:\projects\omr\fvtest\tril\tril\ilgen.hpp(25): fatal error C1083: Cannot open include file: 'ilgen/TypeDictionary.hpp': No such file or directory [C:\projects\omr\fvtest\tril\tril\tril.vcxproj]
         c:\projects\omr\fvtest\tril\tril\ast.hpp(27): fatal error C1083: Cannot open include file: 'OMR/TypeTraits.hpp': No such file or directory [C:\projects\omr\fvtest\tril\tril\tril.vcxproj]
         c:\projects\omr\fvtest\tril\tril\ast.hpp(27): fatal error C1083: Cannot open include file: 'OMR/TypeTraits.hpp': No such file or directory [C:\projects\omr\fvtest\tril\tril\tril.vcxproj]
         c:\projects\omr\fvtest\tril\tril\method_info.hpp(25): fatal error C1083: Cannot open include file: 'il/DataTypes.hpp': No such file or directory [C:\projects\omr\fvtest\tril\tril\tril.vcxproj]
```
The OMR component are not seen by the tril tests. However, this failure is not seen on my local build where I use `cmake 3.14.3` and `msbuild 16.0.461`

**Comment by wbh123456** [comment]
> The appveyor and the Azure omr windows pipeline are both having include problems:
> 
> ```
>          c:\projects\omr\fvtest\tril\tril\ast.hpp(27): fatal error C1083: Cannot open include file: 'OMR/TypeTraits.hpp': No such file or directory [C:\projects\omr\fvtest\tril\tril\tril.vcxproj]
>          c:\projects\omr\fvtest\tril\tril\ast.hpp(27): fatal error C1083: Cannot open include file: 'OMR/TypeTraits.hpp': No such file or directory [C:\projects\omr\fvtest\tril\tril\tril.vcxproj]
>          c:\projects\omr\fvtest\tril\tril\ilgen.hpp(25): fatal error C1083: Cannot open include file: 'ilgen/TypeDictionary.hpp': No such file or directory [C:\projects\omr\fvtest\tril\tril\tril.vcxproj]
>          c:\projects\omr\fvtest\tril\tril\ast.hpp(27): fatal error C1083: Cannot open include file: 'OMR/TypeTraits.hpp': No such file or directory [C:\projects\omr\fvtest\tril\tril\tril.vcxproj]
>          c:\projects\omr\fvtest\tril\tril\ast.hpp(27): fatal error C1083: Cannot open include file: 'OMR/TypeTraits.hpp': No such file or directory [C:\projects\omr\fvtest\tril\tril\tril.vcxproj]
>          c:\projects\omr\fvtest\tril\tril\method_info.hpp(25): fatal error C1083: Cannot open include file: 'il/DataTypes.hpp': No such file or directory [C:\projects\omr\fvtest\tril\tril\tril.vcxproj]
> ```
> 
> The OMR component are not seen by the tril tests. However, this failure is not seen on my local build where I use `cmake 3.14.3` and `msbuild 16.0.461`

Received a different error message after I linked `omr_base` against tril.
```
d:\a\1\s\fvtest\tril\tril\ilgen.hpp(25): fatal error C1083: Cannot open include file: 'ilgen/TypeDictionary.hpp': No such file or directory [D:\a\1\s\build\fvtest\tril\tril\tril.vcxproj]
  CallConverter.cpp
d:\a\1\s\fvtest\tril\tril\converter.hpp(26): fatal error C1083: Cannot open include file: 'ilgen/TypeDictionary.hpp': No such file or directory [D:\a\1\s\build\fvtest\tril\tril\tril.vcxproj]
  GenericNodeConverter.cpp
d:\a\1\s\fvtest\tril\tril\converter.hpp(26): fatal error C1083: Cannot open include file: 'ilgen/TypeDictionary.hpp': No such file or directory [D:\a\1\s\build\fvtest\tril\tril\tril.vcxproj]
  simple_compiler.cpp
d:\a\1\s\fvtest\tril\tril\method_info.hpp(25): fatal error C1083: Cannot open include file: 'il/DataTypes.hpp': No such file or directory [D:\a\1\s\build\fvtest\tril\tril\tril.vcxproj]
```

**Comment by fjeremic** [comment]
@wbh123456 FYI Tril tests were already running on Windows Azure builds. They were not running on AppVeyor though.

**Comment by wbh123456** [comment]
> @wbh123456 FYI Tril tests were already running on Windows Azure builds. They were not running on AppVeyor though.

I just took a look at one of our newest OMR azure build https://dev.azure.com/eclipse-omr/omr/_build/results?buildId=1278&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=96d68eba-7198-517e-3083-eb7169f4ccb9 , I did not see any tril tests (`comptest` / `triltest`) running on Windows, out of the 23 tests.

**Comment by wbh123456** [comment]
- [ ] Enable tril tests (`comptest` and `triltest`) on Windows build in both `Azure build` and `AppVeyor build`
- [ ] Fix/skip failing test cases in `comptest` on Windows
- [ ] Fix/skip failing test cases in `triltest` on Windows

**Comment by wbh123456** [comment]
`compilertest` is failing at converting negative byte/short values to floating point in X86. Looks like x86 is failing at handling `b2f`, `b2d`, `s2f`, `s2d` ILOpcodes.

**Comment by wbh123456** [comment]
This PR is failling on appveyor due to the old building system our AppVeyor is currently using.

**Comment by fjeremic** [comment]
@genie-omr build all

**Comment by fjeremic** [comment]
@genie-omr build all

**Comment by fjeremic** [comment]
@genie-omr build all

**Comment by fjeremic** [comment]
@genie-omr build all

**Comment by fjeremic** [comment]
@genie-omr build xlinux,osx

**Comment by fjeremic** [comment]
@genie-omr build xlinux32

**Comment by fjeremic** [comment]
@genie-omr build linux_x86

**Comment by fjeremic** [comment]
@genie-omr build x32linux

**Comment by wbh123456** [comment]
This PR is ready for review.

**Comment by wbh123456** [comment]
Ping

File: azure-pipelines.yml [hunk 1]
```diff
@@ -15,7 +15,7 @@ jobs:
  
       - script: |
           set PATH=C:\Program Files (x86)\Windows Kits\10\bin\10.0.16299.0\x64;%PATH%
-          cmake .. -G "Visual Studio 15 2017 Win64" -C../cmake/caches/Windows.cmake .. -DOMR_DDR=0
+          cmake .. -G "Visual Studio 15 2017 Win64" -C../cmake/caches/Windows.cmake .. -DOMR_DDR=0 -DOMR_TEST_COMPILER=ON -DOMR_JITBUILDER_TEST=ON
```
Comment (rwy0717) [inline azure-pipelines.yml:18]: Can we add these options to the Windows.cmake cache file instead?

Comment (fjeremic) [reply azure-pipelines.yml:18]: Let's also migrate the `-DOMR_DDR=0` as well when we make the above change.

Comment (wbh123456) [reply azure-pipelines.yml:18]: The problem with merging these options into Windows.cmake caches file is the Windows Jenkins builds also builds on this cache file. However, the Jenkins is using an older build system that does not support some of the Tril Test infrastructure. I added the options outside the Windows.cmake to avoid this particular problem. But I think we could create a new cmake file for Azure.

Comment (fjeremic) [reply azure-pipelines.yml:18]: > But I think we could create a new cmake file for Azure.

I wouldn't want to complicate things. If we can't migrate to Windows.cmake I'm ok leaving them here.

**Comment by 0xdaryl** [comment]
The code changes look fine.  A few minor typographical issues to fix please:
* b22b96e904199c4826032a2b28b34865b8b6c347
   * the word-wrapping of the commit message is a bit inconsistent.  Can you make it so?
* 8149c7a79658d9f25a926e69b00ee557ed11778c
   * start the commit title with a capital letter
   * fix typo "am" -> "an"
* 3e41fa9168d42b0113764cb7d5a0fcc87492876a
   * in the commit title, "Arguemnts" -> "Arguments"
   * in the commit body, "crushes" -> "crashes"
* 9ac0742e8af375f593415cb0f80fa4d657f6ca6d
   * in the commit body, "warining" -> "warning"

**Comment by wbh123456** [comment]
> The code changes look fine. A few minor typographical issues to fix please:
> 
> * [b22b96e](https://github.com/eclipse/omr/commit/b22b96e904199c4826032a2b28b34865b8b6c347)
>   
>   * the word-wrapping of the commit message is a bit inconsistent.  Can you make it so?
> * [8149c7a](https://github.com/eclipse/omr/commit/8149c7a79658d9f25a926e69b00ee557ed11778c)
>   
>   * start the commit title with a capital letter
>   * fix typo "am" -> "an"
> * [3e41fa9](https://github.com/eclipse/omr/commit/3e41fa9168d42b0113764cb7d5a0fcc87492876a)
>   
>   * in the commit title, "Arguemnts" -> "Arguments"
>   * in the commit body, "crushes" -> "crashes"
> * [9ac0742](https://github.com/eclipse/omr/commit/9ac0742e8af375f593415cb0f80fa4d657f6ca6d)
>   
>   * in the commit body, "warining" -> "warning"

Sorry for the typo and confusions I created. I have fixed the mistakes and typos in the new force push.

**Comment by fjeremic** [comment]
@genie-omr build all

**Comment by 0xdaryl** [comment]
Looks good except the word wrapping in 57ef1ef56968dbd521ef119acdd59fbc641d3bb3 didn't seem to get fixed.  See the lines ending in "...we are explicitly specifying..." and "...the type of the..." as an example that leaves a single word on the next line.

Once fixed we can just merge this without re-running CI as the one launched this afternoon passed.

**Comment by wbh123456** [comment]
> Looks good except the word wrapping in [57ef1ef](https://github.com/eclipse/omr/commit/57ef1ef56968dbd521ef119acdd59fbc641d3bb3) didn't seem to get fixed. See the lines ending in "...we are explicitly specifying..." and "...the type of the..." as an example that leaves a single word on the next line.
> 
> Once fixed we can just merge this without re-running CI as the one launched this afternoon passed.

Fixed in the new push.
