### PR TITLE
Fix processing of verbose options

### PR DESCRIPTION
**Pull request by mpirvu**
This commit fixes a bug introduced by PR #1007.
The new implementation of setVerboseBitsInJitPrivateConfig() is able to find
the JitConfig without looking at the value of parameter 'base'. However,
when trying to set the verbose flags in PrivateJitConfig for the trj9
subproject it uses setVerboseBits() which, similarly, was changed to
ignore the parameter 'base' and retrieve the OMR JitConfig from _feBase.
This is wrong.
The solution is to factor out the commong code that sets verbose bits
and call it from two different places:
1) setVerboseBitsInJitPrivateConfig() used by trj9 subproject
2) setVerboseBits() used by OMR generic code

Issue: #1085
Signed-off-by: Marius Pirvu <mpirvu@ca.ibm.com>

### CODE REVIEW

**Comment by ncough** [comment]
This change is failing in my local build due to `TR_Debug::dumpOptions`. Its unhappy when performing a comparison with the overloaded `setVerboseBits()`:

`../omr/compiler/ras/OptionsDebug.cpp:382: error: assuming cast to type ‘char* (*)(char*, void*, TR::OptionTable*)’ from overloaded function`

**Comment by mpirvu** [comment]
The code compiled on my laptop, but apparently Linux complains about the overload. I have changed the name of the helper from the overloaded setVerboseBits() to setVerboseBitsHelper()

**Comment by ncough** [comment]
LGTM, thanks for fixing the issue.

**Comment by mpirvu** [comment]
Everything is good now. PR is ready to be merged.
