### PR TITLE
Build Compilation issue with count static variable on z/TPF.

### PR DESCRIPTION
**Pull request by jjohnst-us**
z/TPF uses GCC 4.6.3 compiler and there appears to be a bug in the
compiler trying to resolve the static count variable.  The 
compilation error goes away if we simply rename the variable to 
_count.

Signed-off-by: jjohnst-us <jjohnst@us.ibm.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
What is the compilation error this PR averts?

**Comment by jjohnst-us** [comment]
@0xdaryl , I rebased just because I saw an unrelated Travis CI build failure, and it appeared to clear-up after the rebase.
Here is the compilation error we see without this pull request modification:
tpf-g++ -DSUPPORTS_THREAD_LOCAL -D_ZTPF_WANTS_ATOE_FUNCTIONALITY -std=c++0x -fno-rtti -fno-threadsafe-statics -Wno-deprecated -Wno-enum-compare -Wno-invalid-offsetof -Wno-write-strings -I/projects/jvmport/userfiles/base/a2e/headers -I/ztpf/commit/base/a2e/headers -isystem /projects/jvmport/userfiles/opensource/include -isystem /ztpf/commit/opensource/include -isystem /projects/jvmport/userfiles/opensource/include46/g++ -isystem /ztpf/commit/opensource/include46/g++ -isystem /projects/jvmport/userfiles/opensource/include46/g++/backward -isystem /ztpf/commit/opensource/include46/g++/backward -isystem /projects/jvmport/userfiles -isystem /ztpf/commit -isystem /projects/jvmport/userfiles/base/include -isystem /ztpf/commit/base/include -isystem /projects/jvmport/userfiles/noship/include -isystem /ztpf/commit/noship/include -I/projects/jvmport/userfiles/base/include -I/ztpf/commit/base/include -I/projects/jvmport/userfiles/opensource/include -I/ztpf/commit/opensource/include -I/projects/jvmport/userfiles/opensource/include46/g++ -I/ztpf/commit/opensource/include46/g++ -I/projects/jvmport/userfiles/opensource/include46/g++/backward -I/ztpf/commit/opensource/include46/g++/backward -I/projects/jvmport/userfiles/base/include -I/ztpf/commit/base/include -D_TPF_SOURCE -DJ9ZTPF -DOMRZTPF -DLINUX -DZTPF_POSIX_SOCKET -DTR_HOST_S390 -DTR_TARGET_S390 -DTR_HOST_64BIT -DTR_TARGET_64BIT -DBITVECTOR_64BIT -DFULL_ANSI -DMAXMOVE -DIBM_ATOE -D_GNU_SOURCE -D_PORTABLE_TPF_SIGINFO -fomit-frame-pointer -fasynchronous-unwind-tables -Wreturn-type -fno-dollars-in-identifiers -fPIC -fno-strict-aliasing -march=z10 -mtune=z9-109 -mzarch -O3   -DBITVECTOR_BIT_NUMBERING_MSB -DUT_DIRECT_TRACE_REGISTRATION -DJ9_PROJECT_SPECIFIC -DJAVA_SPEC_VERSION=8 -DJ9VM_OPT_JAVA_CRYPTO_ACCELERATION -DBUILD_Z_RUNTIME_INSTRUMENTATION -DTR_HOST_S390 -DTR_HOST_64BIT -DBITVECTOR_64BIT -DLINUX -DTR_TARGET_S390 -DTR_TARGET_64BIT -D_LONG_LONG -DS390 -DS39064 -DFULL_ANSI -DMAXMOVE -DJ9VM_TIERED_CODE_CACHE -I'/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../omr/include_core' -I'/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../omr/thread' -I'/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../omr/gc/include' -I'/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../tr.source/trj9/z/' -I'/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../tr.source/trj9/z' -I'/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../tr.source/trj9' -I'/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../tr.source' -I'/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../omr/compiler/z/' -I'/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../omr/compiler/z' -I'/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../omr/compiler' -I'/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../omr' -I'/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/..' -I'/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../codert_vm' -I'/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../gc_include' -I'/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../include' -I'/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../gc_glue_java' -I'/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../jit_vm' -I'/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../nls' -I'/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../oti' -I'/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../util' -MMD -MF /cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../objs/omr/compiler/control/OMROptions.o.depend.mk -MT /cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../objs/omr/compiler/control/OMROptions.o -MP -o /cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../objs/omr/compiler/control/OMROptions.o -c /cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../omr/compiler/control/OMROptions.cpp
/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../omr/compiler/control/OMROptions.cpp: In member function 'char* OMR::Options::setCounts()':
/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../omr/compiler/control/OMROptions.cpp:4146:7: error: reference to 'count' is ambiguous
/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../omr/compiler/control/OMROptions.cpp:4004:19: error: candidates are: int32_t count [8]
/ztpf/commit/opensource/include46/g++/bits/stl_algo.h:4582:5: error:                 template<class _IIter, class _Tp> typename std::iterator_traits<_InputIterator>::difference_type std::count(_IIter, _IIter, const _Tp&)
/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../omr/compiler/control/OMROptions.cpp:4157:13: error: reference to 'count' is ambiguous
/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../omr/compiler/control/OMROptions.cpp:4004:19: error: candidates are: int32_t count [8]
0
/ztpf/commit/opensource/include46/g++/bits/stl_algo.h:4582:5: error:                 template<class _IIter, class _Tp> typename std::iterator_traits<_InputIterator>::difference_type std::count(_IIter, _IIter, const _Tp&)
/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../omr/compiler/control/OMROptions.cpp:4163:20: error: reference to 'count' is ambiguous
/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../omr/compiler/control/OMROptions.cpp:4004:19: error: candidates are: int32_t count [8]
/ztpf/commit/opensource/include46/g++/bits/stl_algo.h:4582:5: error:                 template<class _IIter, class _Tp> typename std::iterator_traits<_InputIterator>::difference_type std::count(_IIter, _IIter, const _Tp&)
/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../omr/compiler/control/OMROptions.cpp:4164:19: error: reference to 'count' is ambiguous
/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../omr/compiler/control/OMROptions.cpp:4004:19: error: candidates are: int32_t count [8]
/ztpf/commit/opensource/include46/g++/bits/stl_algo.h:4582:5: error:                 template<class _IIter, class _Tp> typename std::iterator_traits<_InputIterator>::difference_type std::count(_IIter, _IIter, const _Tp&)
/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../omr/compiler/control/OMROptions.cpp:4168:31: error: reference to 'count' is ambiguous
/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../omr/compiler/control/OMROptions.cpp:4004:19: error: candidates are: int32_t count [8]
/ztpf/commit/opensource/include46/g++/bits/stl_algo.h:4582:5: error:                 template<class _IIter, class _Tp> typename std::iterator_traits<_InputIterator>::difference_type std::count(_IIter, _IIter, const _Tp&)
/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../omr/compiler/control/OMROptions.cpp:4173:13: error: reference to 'count' is ambiguous
/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../omr/compiler/control/OMROptions.cpp:4004:19: error: candidates are: int32_t count [8]
/ztpf/commit/opensource/include46/g++/bits/stl_algo.h:4582:5: error:                 template<class _IIter, class _Tp> typename std::iterator_traits<_InputIterator>::difference_type std::count(_IIter, _IIter, const _Tp&)
/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../omr/compiler/control/OMROptions.cpp:4177:13: error: reference to 'count' is ambiguous
/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../omr/compiler/control/OMROptions.cpp:4004:19: error: candidates are: int32_t count [8]
/ztpf/commit/opensource/include46/g++/bits/stl_algo.h:4582:5: error:                 template<class _IIter, class _Tp> typename std::iterator_traits<_InputIterator>::difference_type std::count(_IIter, _IIter, const _Tp&)
/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../omr/compiler/control/OMROptions.cpp: In member function 'TR_Hotness OMR::Options::getNextHotnessLevel(bool, TR_Hotness)':
/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../omr/compiler/control/OMROptions.cpp:4263:48: error: reference to 'count' is ambiguous
/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../omr/compiler/control/OMROptions.cpp:4004:19: error: candidates are: int32_t count [8]
/ztpf/commit/opensource/include46/g++/bits/stl_algo.h:4582:5: error:                 template<class _IIter, class _Tp> typename std::iterator_traits<_InputIterator>::difference_type std::count(_IIter, _IIter, const _Tp&)
/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../omr/compiler/control/OMROptions.cpp: In member function 'int32_t OMR::Options::getCountValue(bool, TR_Hotness)':
/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../omr/compiler/control/OMROptions.cpp:4284:49: error: reference to 'count' is ambiguous
/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../omr/compiler/control/OMROptions.cpp:4004:19: error: candidates are: int32_t count [8]
/ztpf/commit/opensource/include46/g++/bits/stl_algo.h:4582:5: error:                 template<class _IIter, class _Tp> typename std::iterator_traits<_InputIterator>::difference_type std::count(_IIter, _IIter, const _Tp&)
/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../omr/compiler/control/OMROptions.cpp: In static member function 'static TR_Hotness OMR::Options::getInitialHotnessLevel(bool)':
/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../omr/compiler/control/OMROptions.cpp:4291:48: error: reference to 'count' is ambiguous
/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../omr/compiler/control/OMROptions.cpp:4004:19: error: candidates are: int32_t count [8]
/ztpf/commit/opensource/include46/g++/bits/stl_algo.h:4582:5: error:                 template<class _IIter, class _Tp> typename std::iterator_traits<_InputIterator>::difference_type std::count(_IIter, _IIter, const _Tp&)
/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../omr/compiler/control/OMROptions.cpp: In member function 'int32_t OMR::Options::getCountValue(bool, TR_Hotness)':
/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../omr/compiler/control/OMROptions.cpp: In member function 'int32_t OMR::Options::getCountValue(bool, TR_Hotness)':
/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../omr/compiler/control/OMROptions.cpp:4284:49: error: reference to 'count' is ambiguous
/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../omr/compiler/control/OMROptions.cpp:4004:19: error: candidates are: int32_t count [8]
/ztpf/commit/opensource/include46/g++/bits/stl_algo.h:4582:5: error:                 template<class _IIter, class _Tp> typename std::iterator_traits<_InputIterator>::difference_type std::count(_IIter, _IIter, const _Tp&)
/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../omr/compiler/control/OMROptions.cpp: In static member function 'static TR_Hotness OMR::Options::getInitialHotnessLevel(bool)':
/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../omr/compiler/control/OMROptions.cpp:4291:48: error: reference to 'count' is ambiguous
/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../omr/compiler/control/OMROptions.cpp:4004:19: error: candidates are: int32_t count [8]
/ztpf/commit/opensource/include46/g++/bits/stl_algo.h:4582:5: error:                 template<class _IIter, class _Tp> typename std::iterator_traits<_InputIterator>::difference_type std::count(_IIter, _IIter, const _Tp&)
/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../omr/compiler/control/OMROptions.cpp: In member function 'int32_t OMR::Options::getCountValue(bool, TR_Hotness)':
/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../omr/compiler/control/OMROptions.cpp:4285:4: warning: control reaches end of non-void function [-Wreturn-type]
/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../tr.source/trj9/build/rules/ztpf-gcc/common.mk:65: recipe for target '/cteam/jjohnst/javabld/currentbuild/tmp/bld_372016/bld_linux_ztpf_390-64/tr.source/../objs/omr/compiler/control/OMROptions.o' failed

**Comment by jjohnst-us** [comment]
It's almost as if the compiler is getting confused about the scope of the 'count' variable.  By renaming it it somehow bypasses the issue and can resolve it.

The variable is static and only used in this segment.  I would even argue the update makes the code more readable, because count is also used in a local scope capacity in the same segment.

**Comment by jjohnst-us** [comment]
@fjeremic @0xdaryl 
Do you know who is appropriate for JIT OMR reviews?  Thanks!

**Comment by mstoodle** [comment]
@jjohnst-us Wouldn't it be cleaner to just make these arrays to be private static fields of the OMR::Options class, since they only seem to be referenced by OMR::Options functions?

I can't see why these arrays should be file scoped globals outside of the OMR::Options class (to compete with std::count like this). Though, without a "using namespace std" in the file, I'm not sure why the compiler sees fit to confuse the names anyway...

**Comment by jjohnst-us** [comment]
@mstoodle Thank you, withdrawing and fixing on our end.

**Comment by jjohnst-us** [comment]
Fixing our C++ header which is incorrectly specifying using namespace std; unconditionally.
